// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"example.com/work-demo/internal/service/test/internal/biz"
	"example.com/work-demo/internal/service/test/internal/transport"
)

// Injectors from wire.go:

func newServer() (*transport.Server, error) {
	string2 := defaultAddress()
	service := biz.New()
	server := transport.New(string2, service)
	return server, nil
}
