// Code generated by hertz generator.

package work

import (
	"context"
	"net/http"
	"strconv"

	client "example.com/work-demo/internal/gateway/client"
	workmodel "example.com/work-demo/internal/gateway/model/work"
	userpb "example.com/work-demo/kitex_gen/user"
	workpb "example.com/work-demo/kitex_gen/work"
	"github.com/cloudwego/hertz/pkg/app"
)

// GetWork is the handler referenced by the Hertz-generated route.
func GetWork(ctx context.Context, c *app.RequestContext) {
	clients := client.Get()

	workID, err := strconv.ParseInt(c.Param("workID"), 10, 64)
	if err != nil || workID <= 0 {
		c.JSON(http.StatusBadRequest, map[string]string{"message": "invalid workID"})
		return
	}
	workResult, err := clients.Work().GetWork(ctx, &workpb.GetWorkRequest{WorkId: workID})
	if err != nil {
		c.JSON(http.StatusInternalServerError, map[string]string{"message": "get work failed"})
		return
	}

	workItem := workResult.GetWork()
	userResult, err := clients.User().GetUser(ctx, &userpb.GetUserRequest{UserId: workItem.GetUserId()})
	if err != nil {
		c.JSON(http.StatusInternalServerError, map[string]string{"message": "get user failed"})
		return
	}

	user := userResult.GetUser()
	c.JSON(http.StatusOK, &workmodel.GetWorkResponse{
		Id:   workItem.GetId(),
		Name: workItem.GetName(),
		User: &workmodel.User{Id: user.GetId(), Name: user.GetName()},
	})
}
