// Code generated by hertz generator.

package sum

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addMw() []app.HandlerFunc {
	// your code...
	return nil
}
