// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"example.com/work-demo/internal/service/user/internal/biz"
	"example.com/work-demo/internal/service/user/internal/data"
	"example.com/work-demo/internal/service/user/internal/transport"
)

// Injectors from wire.go:

func newServer() (*transport.Server, error) {
	string2 := defaultAddress()
	client, err := data.OpenDB()
	if err != nil {
		return nil, err
	}
	userRepository := data.NewUserRepository(client)
	service := biz.New(userRepository)
	server := transport.New(string2, client, service)
	return server, nil
}
