// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

#include "api.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace api {
}  // namespace api
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_api_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_api_2eproto = nullptr;
const uint32_t TableStruct_api_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_api_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\tapi.proto\022\003api\032 google/protobuf/descri"
  "ptor.proto:1\n\010raw_body\022\035.google.protobuf"
  ".FieldOptions\030\265\207\003 \001(\t:.\n\005query\022\035.google."
  "protobuf.FieldOptions\030\266\207\003 \001(\t:/\n\006header\022"
  "\035.google.protobuf.FieldOptions\030\267\207\003 \001(\t:/"
  "\n\006cookie\022\035.google.protobuf.FieldOptions\030"
  "\270\207\003 \001(\t:-\n\004body\022\035.google.protobuf.FieldO"
  "ptions\030\271\207\003 \001(\t:-\n\004path\022\035.google.protobuf"
  ".FieldOptions\030\272\207\003 \001(\t:+\n\002vd\022\035.google.pro"
  "tobuf.FieldOptions\030\273\207\003 \001(\t:-\n\004form\022\035.goo"
  "gle.protobuf.FieldOptions\030\274\207\003 \001(\t:0\n\007js_"
  "conv\022\035.google.protobuf.FieldOptions\030\275\207\003 "
  "\001(\t:2\n\tfile_name\022\035.google.protobuf.Field"
  "Options\030\276\207\003 \001(\t:-\n\004none\022\035.google.protobu"
  "f.FieldOptions\030\277\207\003 \001(\t:8\n\017form_compatibl"
  "e\022\035.google.protobuf.FieldOptions\030\323\207\003 \001(\t"
  ":;\n\022js_conv_compatible\022\035.google.protobuf"
  ".FieldOptions\030\324\207\003 \001(\t:=\n\024file_name_compa"
  "tible\022\035.google.protobuf.FieldOptions\030\325\207\003"
  " \001(\t:8\n\017none_compatible\022\035.google.protobu"
  "f.FieldOptions\030\326\207\003 \001(\t:/\n\006go_tag\022\035.googl"
  "e.protobuf.FieldOptions\030\271\216\003 \001(\t:-\n\003get\022\036"
  ".google.protobuf.MethodOptions\030\231\210\003 \001(\t:."
  "\n\004post\022\036.google.protobuf.MethodOptions\030\232"
  "\210\003 \001(\t:-\n\003put\022\036.google.protobuf.MethodOp"
  "tions\030\233\210\003 \001(\t:0\n\006delete\022\036.google.protobu"
  "f.MethodOptions\030\234\210\003 \001(\t:/\n\005patch\022\036.googl"
  "e.protobuf.MethodOptions\030\235\210\003 \001(\t:1\n\007opti"
  "ons\022\036.google.protobuf.MethodOptions\030\236\210\003 "
  "\001(\t:.\n\004head\022\036.google.protobuf.MethodOpti"
  "ons\030\237\210\003 \001(\t:-\n\003any\022\036.google.protobuf.Met"
  "hodOptions\030\240\210\003 \001(\t:2\n\010gen_path\022\036.google."
  "protobuf.MethodOptions\030\375\210\003 \001(\t:5\n\013api_ve"
  "rsion\022\036.google.protobuf.MethodOptions\030\376\210"
  "\003 \001(\t:-\n\003tag\022\036.google.protobuf.MethodOpt"
  "ions\030\377\210\003 \001(\t:.\n\004name\022\036.google.protobuf.M"
  "ethodOptions\030\200\211\003 \001(\t:3\n\tapi_level\022\036.goog"
  "le.protobuf.MethodOptions\030\201\211\003 \001(\t:4\n\nser"
  "ializer\022\036.google.protobuf.MethodOptions\030"
  "\202\211\003 \001(\t:/\n\005param\022\036.google.protobuf.Metho"
  "dOptions\030\203\211\003 \001(\t:1\n\007baseurl\022\036.google.pro"
  "tobuf.MethodOptions\030\204\211\003 \001(\t:6\n\014handler_p"
  "ath\022\036.google.protobuf.MethodOptions\030\205\211\003 "
  "\001(\t:A\n\027handler_path_compatible\022\036.google."
  "protobuf.MethodOptions\030\233\211\003 \001(\t:6\n\thttp_c"
  "ode\022!.google.protobuf.EnumValueOptions\030\341"
  "\211\003 \001(\005:6\n\013base_domain\022\037.google.protobuf."
  "ServiceOptions\030\342\211\003 \001(\t:A\n\026base_domain_co"
  "mpatible\022\037.google.protobuf.ServiceOption"
  "s\030\253\214\003 \001(\t:7\n\014service_path\022\037.google.proto"
  "buf.ServiceOptions\030\254\214\003 \001(\t:2\n\007reserve\022\037."
  "google.protobuf.MessageOptions\030\216\215\003 \001(\tB\006"
  "Z\004/api"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_api_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::_pbi::once_flag descriptor_table_api_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_api_2eproto = {
    false, false, 2086, descriptor_table_protodef_api_2eproto,
    "api.proto",
    &descriptor_table_api_2eproto_once, descriptor_table_api_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_api_2eproto::offsets,
    nullptr, file_level_enum_descriptors_api_2eproto,
    file_level_service_descriptors_api_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_api_2eproto_getter() {
  return &descriptor_table_api_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_api_2eproto(&descriptor_table_api_2eproto);
namespace api {
const std::string raw_body_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  raw_body(kRawBodyFieldNumber, raw_body_default, nullptr);
const std::string query_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  query(kQueryFieldNumber, query_default, nullptr);
const std::string header_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  header(kHeaderFieldNumber, header_default, nullptr);
const std::string cookie_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  cookie(kCookieFieldNumber, cookie_default, nullptr);
const std::string body_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  body(kBodyFieldNumber, body_default, nullptr);
const std::string path_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  path(kPathFieldNumber, path_default, nullptr);
const std::string vd_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  vd(kVdFieldNumber, vd_default, nullptr);
const std::string form_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  form(kFormFieldNumber, form_default, nullptr);
const std::string js_conv_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  js_conv(kJsConvFieldNumber, js_conv_default, nullptr);
const std::string file_name_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  file_name(kFileNameFieldNumber, file_name_default, nullptr);
const std::string none_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  none(kNoneFieldNumber, none_default, nullptr);
const std::string form_compatible_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  form_compatible(kFormCompatibleFieldNumber, form_compatible_default, nullptr);
const std::string js_conv_compatible_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  js_conv_compatible(kJsConvCompatibleFieldNumber, js_conv_compatible_default, nullptr);
const std::string file_name_compatible_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  file_name_compatible(kFileNameCompatibleFieldNumber, file_name_compatible_default, nullptr);
const std::string none_compatible_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  none_compatible(kNoneCompatibleFieldNumber, none_compatible_default, nullptr);
const std::string go_tag_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  go_tag(kGoTagFieldNumber, go_tag_default, nullptr);
const std::string get_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  get(kGetFieldNumber, get_default, nullptr);
const std::string post_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  post(kPostFieldNumber, post_default, nullptr);
const std::string put_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  put(kPutFieldNumber, put_default, nullptr);
const std::string delete__default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  delete_(kDeleteFieldNumber, delete__default, nullptr);
const std::string patch_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  patch(kPatchFieldNumber, patch_default, nullptr);
const std::string options_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  options(kOptionsFieldNumber, options_default, nullptr);
const std::string head_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  head(kHeadFieldNumber, head_default, nullptr);
const std::string any_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  any(kAnyFieldNumber, any_default, nullptr);
const std::string gen_path_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  gen_path(kGenPathFieldNumber, gen_path_default, nullptr);
const std::string api_version_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  api_version(kApiVersionFieldNumber, api_version_default, nullptr);
const std::string tag_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  tag(kTagFieldNumber, tag_default, nullptr);
const std::string name_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  name(kNameFieldNumber, name_default, nullptr);
const std::string api_level_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  api_level(kApiLevelFieldNumber, api_level_default, nullptr);
const std::string serializer_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  serializer(kSerializerFieldNumber, serializer_default, nullptr);
const std::string param_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  param(kParamFieldNumber, param_default, nullptr);
const std::string baseurl_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  baseurl(kBaseurlFieldNumber, baseurl_default, nullptr);
const std::string handler_path_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  handler_path(kHandlerPathFieldNumber, handler_path_default, nullptr);
const std::string handler_path_compatible_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  handler_path_compatible(kHandlerPathCompatibleFieldNumber, handler_path_compatible_default, nullptr);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< int32_t >, 5, false>
  http_code(kHttpCodeFieldNumber, 0, nullptr);
const std::string base_domain_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::ServiceOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  base_domain(kBaseDomainFieldNumber, base_domain_default, nullptr);
const std::string base_domain_compatible_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::ServiceOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  base_domain_compatible(kBaseDomainCompatibleFieldNumber, base_domain_compatible_default, nullptr);
const std::string service_path_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::ServiceOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  service_path(kServicePathFieldNumber, service_path_default, nullptr);
const std::string reserve_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  reserve(kReserveFieldNumber, reserve_default, nullptr);

// @@protoc_insertion_point(namespace_scope)
}  // namespace api
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
