// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"example.com/work-demo/internal/server/test"
	test2 "example.com/work-demo/internal/service/test"
)

// Injectors from wire.go:

func NewServer() (*test.Server, error) {
	options := test.DefaultOptions()
	service := test2.New()
	server := test.New(options, service)
	return server, nil
}
