// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: user_http.proto

package user

import (
	_ "example.com/work-demo/hertz/biz/model/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" path:"id"`
}

func (x *GetUserNameRequest) Reset() {
	*x = GetUserNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNameRequest) ProtoMessage() {}

func (x *GetUserNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNameRequest.ProtoReflect.Descriptor instead.
func (*GetUserNameRequest) Descriptor() ([]byte, []int) {
	return file_user_http_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserNameRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" form:"name" json:"name,omitempty" query:"name"`
}

func (x *GetUserNameResponse) Reset() {
	*x = GetUserNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_http_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNameResponse) ProtoMessage() {}

func (x *GetUserNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_http_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNameResponse.ProtoReflect.Descriptor instead.
func (*GetUserNameResponse) Descriptor() ([]byte, []int) {
	return file_user_http_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_user_http_proto protoreflect.FileDescriptor

var file_user_http_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x35, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x06, 0xd2, 0xbb, 0x18, 0x02, 0x69,
	0x64, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x32, 0x61, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0e, 0xca, 0xc1, 0x18, 0x0a, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x2f, 0x3a, 0x69, 0x64, 0x42, 0x2c, 0x5a, 0x2a, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x2d, 0x64, 0x65, 0x6d, 0x6f,
	0x2f, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_http_proto_rawDescOnce sync.Once
	file_user_http_proto_rawDescData = file_user_http_proto_rawDesc
)

func file_user_http_proto_rawDescGZIP() []byte {
	file_user_http_proto_rawDescOnce.Do(func() {
		file_user_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_http_proto_rawDescData)
	})
	return file_user_http_proto_rawDescData
}

var file_user_http_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_http_proto_goTypes = []interface{}{
	(*GetUserNameRequest)(nil),  // 0: user.GetUserNameRequest
	(*GetUserNameResponse)(nil), // 1: user.GetUserNameResponse
}
var file_user_http_proto_depIdxs = []int32{
	0, // 0: user.UserService.GetUserName:input_type -> user.GetUserNameRequest
	1, // 1: user.UserService.GetUserName:output_type -> user.GetUserNameResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_http_proto_init() }
func file_user_http_proto_init() {
	if File_user_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_http_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_http_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_http_proto_goTypes,
		DependencyIndexes: file_user_http_proto_depIdxs,
		MessageInfos:      file_user_http_proto_msgTypes,
	}.Build()
	File_user_http_proto = out.File
	file_user_http_proto_rawDesc = nil
	file_user_http_proto_goTypes = nil
	file_user_http_proto_depIdxs = nil
}
