// Code generated by hertz generator.

package work

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _worksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getworkMw() []app.HandlerFunc {
	// your code...
	return nil
}
