// Code generated by Kitex v0.16.3. DO NOT EDIT.

package testservice

import (
	"context"
	"errors"
	testapi "example.com/work-demo/internal/gateway/model/testapi"
	test "example.com/work-demo/kitex_gen/test"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"TestFields": kitex.NewMethodInfo(
		testFieldsHandler,
		newTestFieldsArgs,
		newTestFieldsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	testServiceServiceInfo                = NewServiceInfo()
	testServiceServiceInfoForClient       = NewServiceInfoForClient()
	testServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return testServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return testServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return testServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "TestService"
	handlerType := (*test.TestService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "test",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func testFieldsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(testapi.TestFieldsRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(test.TestService).TestFields(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *TestFieldsArgs:
		success, err := handler.(test.TestService).TestFields(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*TestFieldsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newTestFieldsArgs() interface{} {
	return &TestFieldsArgs{}
}

func newTestFieldsResult() interface{} {
	return &TestFieldsResult{}
}

type TestFieldsArgs struct {
	Req *testapi.TestFieldsRequest
}

func (p *TestFieldsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *TestFieldsArgs) Unmarshal(in []byte) error {
	msg := new(testapi.TestFieldsRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var TestFieldsArgs_Req_DEFAULT *testapi.TestFieldsRequest

func (p *TestFieldsArgs) GetReq() *testapi.TestFieldsRequest {
	if !p.IsSetReq() {
		return TestFieldsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *TestFieldsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TestFieldsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type TestFieldsResult struct {
	Success *testapi.TestFieldsResponse
}

var TestFieldsResult_Success_DEFAULT *testapi.TestFieldsResponse

func (p *TestFieldsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *TestFieldsResult) Unmarshal(in []byte) error {
	msg := new(testapi.TestFieldsResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *TestFieldsResult) GetSuccess() *testapi.TestFieldsResponse {
	if !p.IsSetSuccess() {
		return TestFieldsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *TestFieldsResult) SetSuccess(x interface{}) {
	p.Success = x.(*testapi.TestFieldsResponse)
}

func (p *TestFieldsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TestFieldsResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) TestFields(ctx context.Context, Req *testapi.TestFieldsRequest) (r *testapi.TestFieldsResponse, err error) {
	var _args TestFieldsArgs
	_args.Req = Req
	var _result TestFieldsResult
	if err = p.c.Call(ctx, "TestFields", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
