// Code generated by hertz generator.

package testapi

import "github.com/cloudwego/hertz/pkg/app"

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testfieldsMw() []app.HandlerFunc {
	// your code...
	return nil
}
