// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package work

import (
	"example.com/work-demo/internal/server/work"
	work2 "example.com/work-demo/internal/service/work"
	"example.com/work-demo/internal/service/work/data"
)

// Injectors from wire.go:

func NewServer() (*work.Server, error) {
	options := work.DefaultOptions()
	client, err := data.OpenDB()
	if err != nil {
		return nil, err
	}
	workRepository := data.NewWorkRepository(client)
	service := work2.New(workRepository)
	server := work.New(options, client, service)
	return server, nil
}
