// Code generated by Kitex v0.16.3. DO NOT EDIT.

package user

import (
	"context"

	"github.com/cloudwego/prutal"
)

type GetUserRequest struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *GetUserRequest) Reset() { *x = GetUserRequest{} }

func (x *GetUserRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type User struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (x *User) Reset() { *x = User{} }

func (x *User) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *User) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (x *GetUserResponse) Reset() { *x = GetUserResponse{} }

func (x *GetUserResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetUserResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserService interface {
	GetUser(ctx context.Context, req *GetUserRequest) (res *GetUserResponse, err error)
}
