// Code generated by Kitex v0.16.3. DO NOT EDIT.

package work

import (
	"context"

	"github.com/cloudwego/prutal"
)

type GetWorkRequest struct {
	WorkId int64 `protobuf:"varint,1,opt,name=work_id" json:"work_id,omitempty"`
}

func (x *GetWorkRequest) Reset() { *x = GetWorkRequest{} }

func (x *GetWorkRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetWorkRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetWorkRequest) GetWorkId() int64 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

type Work struct {
	Id     int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	UserId int64  `protobuf:"varint,3,opt,name=user_id" json:"user_id,omitempty"`
}

func (x *Work) Reset() { *x = Work{} }

func (x *Work) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Work) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Work) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Work) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Work) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetWorkResponse struct {
	Work *Work `protobuf:"bytes,1,opt,name=work" json:"work,omitempty"`
}

func (x *GetWorkResponse) Reset() { *x = GetWorkResponse{} }

func (x *GetWorkResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *GetWorkResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *GetWorkResponse) GetWork() *Work {
	if x != nil {
		return x.Work
	}
	return nil
}

type WorkService interface {
	GetWork(ctx context.Context, req *GetWorkRequest) (res *GetWorkResponse, err error)
}
