// Code generated by Kitex v0.16.3. DO NOT EDIT.

package workservice

import (
	"context"
	"errors"
	work "example.com/work-demo/service/work/kitex_gen/work"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetWork": kitex.NewMethodInfo(
		getWorkHandler,
		newGetWorkArgs,
		newGetWorkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	workServiceServiceInfo                = NewServiceInfo()
	workServiceServiceInfoForClient       = NewServiceInfoForClient()
	workServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return workServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return workServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return workServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "WorkService"
	handlerType := (*work.WorkService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "work",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func getWorkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(work.GetWorkRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(work.WorkService).GetWork(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetWorkArgs:
		success, err := handler.(work.WorkService).GetWork(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetWorkResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetWorkArgs() interface{} {
	return &GetWorkArgs{}
}

func newGetWorkResult() interface{} {
	return &GetWorkResult{}
}

type GetWorkArgs struct {
	Req *work.GetWorkRequest
}

func (p *GetWorkArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetWorkArgs) Unmarshal(in []byte) error {
	msg := new(work.GetWorkRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetWorkArgs_Req_DEFAULT *work.GetWorkRequest

func (p *GetWorkArgs) GetReq() *work.GetWorkRequest {
	if !p.IsSetReq() {
		return GetWorkArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetWorkArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetWorkArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetWorkResult struct {
	Success *work.GetWorkResponse
}

var GetWorkResult_Success_DEFAULT *work.GetWorkResponse

func (p *GetWorkResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetWorkResult) Unmarshal(in []byte) error {
	msg := new(work.GetWorkResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetWorkResult) GetSuccess() *work.GetWorkResponse {
	if !p.IsSetSuccess() {
		return GetWorkResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetWorkResult) SetSuccess(x interface{}) {
	p.Success = x.(*work.GetWorkResponse)
}

func (p *GetWorkResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetWorkResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetWork(ctx context.Context, Req *work.GetWorkRequest) (r *work.GetWorkResponse, err error) {
	var _args GetWorkArgs
	_args.Req = Req
	var _result GetWorkResult
	if err = p.c.Call(ctx, "GetWork", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
