// Code generated by hertz generator.

package sum

import (
	"context"

	sum "example.com/work-demo/internal/gateway/model/sum"
	"example.com/work-demo/internal/gateway/registry"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Add .
// @router /sum [GET]
func Add(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sum.AddRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := registry.GetServices().Sum().Add(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
