// Code generated by Kitex v0.16.3. DO NOT EDIT.

package test

import (
	"context"
	"example.com/work-demo/internal/gateway/model/testapi"
)

type TestService interface {
	TestFields(ctx context.Context, req *testapi.TestFieldsRequest) (res *testapi.TestFieldsResponse, err error)
}
