// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	sum "example.com/work-demo/internal/gateway/router/sum"
	testapi "example.com/work-demo/internal/gateway/router/testapi"
	work "example.com/work-demo/internal/gateway/router/work"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	sum.Register(r)

	work.Register(r)

	testapi.Register(r)
}
