// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gateway

import (
	"example.com/work-demo/internal/gateway/registry"
	"example.com/work-demo/internal/server/gateway"
	"example.com/work-demo/internal/service/sum"
)

// Injectors from wire.go:

func NewServer() (*gateway.Server, error) {
	options := gateway.DefaultOptions()
	testClient, err := gateway.ProvideTestClient(options)
	if err != nil {
		return nil, err
	}
	testJSONClient, err := gateway.ProvideTestJSONClient(options)
	if err != nil {
		return nil, err
	}
	client, err := gateway.ProvideUserClient(options)
	if err != nil {
		return nil, err
	}
	workserviceClient, err := gateway.ProvideWorkClient(options)
	if err != nil {
		return nil, err
	}
	registryRegistry := registry.NewClientRegistry(testClient, testJSONClient, client, workserviceClient)
	service := sum.New()
	serviceRegistry := registry.NewServiceRegistry(service)
	server := gateway.New(options, registryRegistry, serviceRegistry)
	return server, nil
}
