// Code generated by hertz generator.

package test

import (
	"context"
	"encoding/json"

	kitexuser "example.com/work-demo/common/kitex_gen/test"
	test "example.com/work-demo/hertz/biz/model/test"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// TestFields .
// @router /test-fields [POST]
func TestFields(ctx context.Context, c *app.RequestContext) {
	var err error
	var req test.TestFieldsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	payload, err := json.Marshal(req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	rpcReq := new(kitexuser.TestFieldsRequest)
	if err = json.Unmarshal(payload, rpcReq); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	rpcResp, err := rpcClient.TestFields(ctx, rpcReq)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	payload, err = json.Marshal(rpcResp)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	resp := new(test.TestFieldsResponse)
	if err = json.Unmarshal(payload, resp); err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp)
}
