// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gateway

import (
	"example.com/work-demo/internal/gateway/biz/sum"
	"example.com/work-demo/internal/gateway/registry"
)

// Injectors from wire.go:

func newServer() (*Server, error) {
	options := DefaultOptions()
	testClient, err := ProvideTestClient(options)
	if err != nil {
		return nil, err
	}
	testJSONClient, err := ProvideTestJSONClient(options)
	if err != nil {
		return nil, err
	}
	client, err := ProvideUserClient(options)
	if err != nil {
		return nil, err
	}
	workserviceClient, err := ProvideWorkClient(options)
	if err != nil {
		return nil, err
	}
	registryRegistry := registry.NewClientRegistry(testClient, testJSONClient, client, workserviceClient)
	service := sum.New()
	serviceRegistry := registry.NewServiceRegistry(service)
	server := New(options, registryRegistry, serviceRegistry)
	return server, nil
}
