// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"example.com/work-demo/internal/server/user"
	user2 "example.com/work-demo/internal/service/user"
	"example.com/work-demo/internal/service/user/data"
)

// Injectors from wire.go:

func NewServer() (*user.Server, error) {
	options := user.DefaultOptions()
	client, err := data.OpenDB()
	if err != nil {
		return nil, err
	}
	userRepository := data.NewUserRepository(client)
	service := user2.New(userRepository)
	server := user.New(options, client, service)
	return server, nil
}
