// Code generated by hertz generator.

package testapi

import (
	"context"

	testapi "example.com/work-demo/internal/gateway/model/testapi"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// TestFields .
// @router /test [POST]
func TestFields(ctx context.Context, c *app.RequestContext) {
	var err error
	var req testapi.TestFieldsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(testapi.TestFieldsResponse)

	c.JSON(consts.StatusOK, resp)
}
