// Code generated by hertz generator.

package testapi

import (
	"context"

	client "example.com/work-demo/internal/gateway/client"
	testapi "example.com/work-demo/internal/gateway/model/testapi"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"google.golang.org/protobuf/proto"
)

// TestFields .
// @router /test-fields [POST]
func TestFields(ctx context.Context, c *app.RequestContext) {
	var err error
	var req testapi.TestFieldsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	requestBytes, err := proto.Marshal(&req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	responseBytes, err := client.GetTest().GenericCall(ctx, "TestFields", requestBytes)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	resp := new(testapi.TestFieldsResponse)
	if err = proto.Unmarshal(responseBytes.([]byte), resp); err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp)
}
