// Code generated by hertz generator.

package testapi

import (
	"context"

	testapi "example.com/work-demo/internal/gateway/model/testapi"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// TestBind binds a protobuf request body and returns its fields as protobuf.
// @router /testBind [POST]
func TestBind(ctx context.Context, c *app.RequestContext) {
	var req testapi.TestBindRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	c.ProtoBuf(consts.StatusOK, &testapi.TestBindResponse{
		Id:   req.GetId(),
		Name: req.GetName(),
	})
}
