// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	test "example.com/work-demo/internal/router/test"
	work "example.com/work-demo/internal/router/work"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	work.Register(r)

	test.Register(r)
}
