// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	testhandler "example.com/work-demo/internal/handler/test"
	work "example.com/work-demo/internal/router/work"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	r.POST("/test-fields", testhandler.TestFields)
	work.Register(r)

}

// Register registers all routes generated from the HTTP IDL.
func Register(r *server.Hertz) {
	GeneratedRegister(r)
}
