// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package work

import (
	"example.com/work-demo/internal/service/work/internal/biz"
	"example.com/work-demo/internal/service/work/internal/data"
	"example.com/work-demo/internal/service/work/internal/transport"
)

// Injectors from wire.go:

func newServer() (*transport.Server, error) {
	string2 := defaultAddress()
	client, err := data.OpenDB()
	if err != nil {
		return nil, err
	}
	workRepository := data.NewWorkRepository(client)
	service := biz.New(workRepository)
	server := transport.New(string2, client, service)
	return server, nil
}
