// Code generated by hertz generator.

package user

import (
	"context"

	user "example.com/work-demo/hertz/biz/model/user"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetUserName .
// @router /users/:id [GET]
func GetUserName(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetUserNameRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.GetUserNameResponse)

	c.JSON(consts.StatusOK, resp)
}
