// Code generated by hertz generator.

package user

import (
	"context"

	kitexuser "example.com/work-demo/common/kitex_gen/user"
	"example.com/work-demo/hertz/biz/model/user"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/kitex/pkg/kerrors"
)

// GetUserName .
// @router /users/:id [GET]
func GetUserName(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetUserNameRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	rpcResp, err := rpcClient.GetUserName(ctx, &kitexuser.GetUserNameRequest{UserId: req.GetUserId()})
	if err != nil {
		if bizErr, ok := kerrors.FromBizStatusError(err); ok {
			c.JSON(int(bizErr.BizStatusCode()), utils.H{"error": bizErr.BizMessage()})
			return
		}
		c.JSON(consts.StatusInternalServerError, utils.H{"error": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, &user.GetUserNameResponse{Name: rpcResp.GetName()})
}
